[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cs2-anticheat"
version = "2.5.0"
description = "Analyse biomécanique et machine learning des replays Counter-Strike 2."
authors = [
    {name = "CS2 AC Team"}
]
dependencies = [
    "demoparser2>=0.41.4",
    "customtkinter>=6.0.0",
    "scikit-learn>=1.3.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "joblib>=1.3.0",
    "watchdog>=6.0.0",
    "pyperclip>=1.8.0",
    "pillow>=10.0.0",
    "darkdetect>=0.8.0",
    "pyarrow>=14.0.0",
    "reportlab>=4.0.0",
    "pyinstaller>=6.0.0"
]
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
cs2-anticheat = "main:main"

[tool.setuptools.packages.find]
include = ["src*"]
